language: node_js
node_js:
  - 8
cache:
  directories:
    - ~/.npm
    - ~/.cache
    - node_modules
env:
  global:
    - NODE_ENV=test
install:
  - npm install
script:
  - npm test
after_success:
  - cd test/unit && bash <(curl -s https://codecov.io/bash)
